dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
      -libboost-test-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -f -T cpplesson_1_cli-0.0.1-Linux.deb -ukolya-spr:$BINTRAY_API_KEY "https://api.bintray.com/content/kolya-spr/training/lesson-1/$TRAVIS_BUILD_NUMBER/cpplesson_1_cli-0.0.1-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
